### ISSUE TITLE
Support SEQUENCE

### ISSUE THREAD

**Issue by quazardous** [jasvrcek/ICS#10]
http://icalevents.com/4437-correct-handling-of-uid-recurrence-id-sequence/

http://www.kanzaki.com/docs/ical/sequence.html

Hi,

great package !

SEQUENCE support is not present. Can you look at it ?

**Comment by jasvrcek** [comment]
@quazardous I'll add support for this in the next week.

**Comment by quazardous** [comment]
@jasvrcek thx a lot I had a lot of trouble with google calendar before I figure out this SEQUENCE stuff

**Comment by jasvrcek** [comment]
@quazardous SEQUENCE support for events is included in the new 0.2 release that just went live.

**Comment by quazardous** [comment]
bravo !
