### ISSUE TITLE
RecurrenceRule, addByMonthDay() and addByMonth()

### ISSUE THREAD

**Issue by AgamlaRage** [jasvrcek/ICS#23]
> https://github.com/jasvrcek/ICS/blob/master/src/Model/Recurrence/RecurrenceRule.php
> @todo BYSECOND, BYMINUTE, BYHOUR, BYMONTHDAY, BYYEARDAY, BYWEEKNO, BYMONTH, BYSETPOS, and WKST 

Hello, I wanted to know 
- if you planned to finish the method **addByMonthDay()** (currently triggering an error with $bySecond)?
- if you planed to implement the method **addByMonth()** ?

If you didn't planned to update it soon, can you give some recommendations on where to start to implement this features ? 

PS: your class is a pleasure to use, I really want to have this features so I could delete my old-homemade class :)

**Comment by jasvrcek** [comment]
Hi @AgamlaRage,

I would appreciate any help - the $bySecond error does look like a typo. I didn't have immediate plans to implement the addByMonth method, so if you would like to please go for it! You would need to look at the ( "BYMONTH" "=" bymolist ) part of the recur-rule-part section on https://tools.ietf.org/html/rfc5545#page-37.

**Comment by AgamlaRage** [comment]
I did something quickly (seems to be ok for me, get the same result from my previous class), this is really a bit of code then I put it here.
I did all modifications here in **Model/Recurrence/RecurrenceRule.php** https://github.com/jasvrcek/ICS/blob/master/src/Model/Recurrence/RecurrenceRule.php


1 - added function **addByMonth()**

```php
    /**
     * @param integer $integer
     * @return \Jsvrcek\ICS\Model\Recurrence\RecurrenceRule
     */
    public function addByMonth($integer)
    {
        $this->validateInteger($integer);
    
        $this->byMonthList[] = $integer;
        return $this;
    }
```

2 - modified function **addByMonthDay()**
line 357
(original)      `$this->byMonthDayList[] = $bySecond;`
(modified)    `$this->byMonthDayList[] = $integer; // $bySecond is not in the function scope`

3 - modified function **__toString**
add before return 

```php
        if ($this->byMonthList)
            $items[] = 'BYMONTH='.implode(',', $this->byMonthList);
      
        if ($this->byMonthDayList)
            $items[] = 'BYMONTHDAY='.implode(',', $this->byMonthDayList);
```

**Comment by jasvrcek** [comment]
@AgamlaRage looks good, if you make a pull request I'll merge it.
