### ISSUE TITLE
Encode newline, commas, semi-colons, backslash in TEXT value types

### ISSUE THREAD

**Issue by jasvrcek** [jasvrcek/ICS#30]
https://tools.ietf.org/html/rfc5545#page-45

**Comment by StewPoll** [comment]
Oh hey - I was just about to ask about this.

I came across an issue where apple's Calendar program appears to expect the `LOCATION` data to be encoded, but doesn't care about `DESCRIPTION` data being encoded.

Google Calendar doesn't appear to care about this at all though.

Would you want a PR to help with this?

From what I can see in the RFC, we don't need to do anything special for `\n` but for `,` and `;` we need to escape those.

I assume you'd want something under the `Formatter` like `getEscapedText` that just does a `pregreplace` for `,` and `;` and replaces with `\,` and `\;`?

**Comment by jasvrcek** [comment]
@StewPoll a PR would be great! Your plan for adding it to `Formatter` sounds good to me.

**Comment by StewPoll** [comment]
Have made some progress: https://github.com/StewPoll/ICS/tree/enhance-escaped-chars

Will try to finish it off in the next few days.

**Comment by jasvrcek** [comment]
Great, looks good!

**Comment by jasvrcek** [comment]
@StewPoll also, please go ahead and add yourself to the Credits section of the README.md file if you want to.

**Comment by jasvrcek** [comment]
Closing, taken care of by @StewPoll in #43
