### ISSUE TITLE
RFC 7986 properties

### ISSUE THREAD

**Issue by StewPoll** [jasvrcek/ICS#41]
Hey there. 

Just wondering if you'd be willing to implement some of the features in [RCF 7986](https://tools.ietf.org/html/rfc7986) that expand on the functionality of iCal files. 

In particular I'm looking at the [IMAGE](https://tools.ietf.org/html/rfc7986#section-5.10) property but I'm certain other properties could be useful for others as well in the future.

Thanks!

**Comment by jasvrcek** [comment]
Hi @StewPoll, sorry for the delay in replying! I don't have the bandwidth to do that right now, but I'm open to adding it if you do a pull request for it.

**Comment by jasvrcek** [comment]
Pull request merged, closing.
