### ISSUE TITLE
Setting image ?

### ISSUE THREAD

**Issue by MatthieuWinalist** [jasvrcek/ICS#44]
Hey,

I was just wondering if the implementation of setImage (on a calendar event) was done ? Because i actually see it in your src, but when i try to use it, I have an error which says : "Call to undefined method Jsvrcek\ICS\Model\Calendar::setImage()"

Thanks.

**Comment by jasvrcek** [comment]
If you see it in the source on github, but it doesn't exist locally for you, you probably need to adjust your composer settings to install the latest commits.
