### ISSUE TITLE
PHP 8.1 compatibility issue

### ISSUE THREAD

**Issue by dataskills** [jasvrcek/ICS#66]
Passing null as the third parameter of `preg_replace()` is deprecated in php 8.1.
In my case this happened at `/jsvrcek/ics/src/Utility/Formatter.php:145`

See image
<img width="836" alt="Screenshot 2023-01-17 at 11 04 01 AM" src="https://user-images.githubusercontent.com/4392698/212988936-872dc6e9-3192-47cd-8f48-229e5c21ee50.png">

**Comment by jasvrcek** [comment]
@dataskills I have now fixed this in https://github.com/jasvrcek/ICS/commit/11a24ac95648d720a1370c5bb20988b1739a63a4
