### ISSUE TITLE
Support for all day event

### ISSUE THREAD

**Issue by sergionegri** [jasvrcek/ICS#8]
First of all thank you for this bundle :)
Maybe I'm missing something but I was not able to set an event as "all day".
Is the feature developed?
Thank you!

**Comment by jasvrcek** [comment]
@sergionegri I have not added a "duration" option for events - as of now the only possibility is to set an end time. I'm not going to have time to add that in the short-term - do you have any interest in developing it? Alternatively you could just use end time to create an event that lasts until the end of a day.

**Comment by sergionegri** [comment]
Thank you for getting back to me @jasvrcek . I'm not talking about a duration option but an "all day" attribute, which is standard for ics. I'm not knowledged enough to play with your code without spending several hours, but in case you or someone can it really takes little (there is no logic, it's simply adding another method that adds another attribute to the file)

**Comment by jasvrcek** [comment]
@sergionegri I don't see an example of an "all day" attribute outlined in the ics spec (http://tools.ietf.org/html/rfc5546). Can you give me an example?

**Comment by sergionegri** [comment]
You are right, apparently applications interprete an event being all day if:
For an "all-day event" and using timeless dates, the DTEND is equal DTSTART plus one day, example all-day event (2007-12-01)
DTSTART;VALUE=DATE:20071201
DTEND;VALUE=DATE:20071202

Even easier to implement

**Comment by jasvrcek** [comment]
Ok, great - I'm closing this issue.
