### ISSUE TITLE
Large files: new project

### ISSUE THREAD

**Issue by thijsw** [jasvrcek/ICS#9]
Hi,

Thanks for creating this library! I think it's very useful. I encountered that with many events, the memory footprint is rather high because all the items are held in memory before being send to the browser eventually.

I made an extension on this library at this location: https://github.com/thijsw/ics-large

Maybe you could mention it somewhere or we could integrate it in this library someway.

(Not an issue per se, feel free to close of course)

**Comment by jasvrcek** [comment]
Hi @thijsw,

Thanks for working on this - I think the idea to manage the memory footprint is a great idea, and I'm into either mentioning the extension or integrating it. At a glance, though, I don't quite understand what's going on with the ICS_Large\Model\CalendarEventList. In your demo at https://github.com/thijsw/ics-large/blob/master/demo/index.php, how would I add say 10 different events?

**Comment by thijsw** [comment]
Hi @jasvrcek,

I've updated the demo, I hope it makes more sense now.

The idea is that the events are retrieved in batches (from e.g., database) via the given closure which the CalendarEventList calls. In order to keep memory footprint low, these batches of objects are outputted as iCal entries via a modified CalendarStream. Memory-wise it doesn't matter anymore if you're outputting say 200 items, or 20.000 items.

**Comment by jasvrcek** [comment]
Hi @thijsw,

Thanks for the update, sorry it's taking me a while to respond! I would like to integrate what you did into this library. What do you think about moving your new classes (ICS_Large\Model\Calendar, ICS_Large\Model\CalendarEventList, ICS_Large\CalendarStream) into a new namespace Jsvrcek\ICS\Batch, so when you create a calendar instance you could either use Jsvrcek\ICS\Model\Calendar or Jsvrcek\ICS\Batch\Model\Calendar depending on your needs?

Another approach would be to move ICS_Large\Model\Calendar to Jsvrcek\ICS\Model\BatchCalendar, and do something similar for your other new classes.

Let me know if favor either of those ideas, or have any other ones!

**Comment by jasvrcek** [comment]
@thijsw I just released a new 0.2 version which incorporates your ideas - thanks for the inspiration!

**Comment by thijsw** [comment]
Super! Thanks for the update, I will redirect to this plugin in the repo I created or remove it altogether
